ajour/ajour

- Cargo.toml
- ajour.yml
- src/addon.rs
- src/config/mod.rs
- src/curse_api.rs
- src/gui/mod.rs
- src/gui/style.rs
- src/gui/update.rs
- src/network.rs
- src/tukui_api.rs
- src/wowinterface_api.rs
- Async HTTP requests. Fixes #23.
- Row titles above addon rows. Fixes https://github.com/casperstorm/ajour/issues/20.
- Disables `Refresh` and `Update all` when theres no addons. Fixes #22.
- Better logic for hiding addons. Fixes #24.
- Increased default font size.
- Adjusted colors on delete button.
- Moved status line to top-row.
> release: beta2

- README.md
Feel free to reformat as you see fit. The dependencies I added are required to get a working build on Ubuntu 20.04
> Add Ubuntu dependencies to README.md

- src/addon.rs
- src/config/mod.rs
- src/config/wow.rs
- src/gui/element.rs
- src/gui/mod.rs
- src/gui/style.rs
- src/gui/update.rs
With this PR I have added the ability to select flavor in settings.
I've also refactored `flavor` from `String` into an enum.
> feat: flavor selection in settings

- Cargo.lock
- Cargo.toml
- src/curse_api.rs
- src/network.rs
- src/tukui_api.rs
- src/wowinterface_api.rs
Small PR with some misc changes:
- Updated [native-dialog](https://crates.io/crates/native-dialog) to newest version. Fixes #51.
- Implemented better timeouts for requests. Fixes #53 .
> hotfix: misc

- src/addon.rs
- src/config/addons.rs
- src/gui/element.rs
- src/gui/mod.rs
- src/gui/style.rs
- src/gui/update.rs
> feat: ignore/unignore addons in settings

- src/addon.rs
- src/gui/element.rs
- src/toc.rs
> feat: added author to details

- src/addon.rs
- src/fs.rs
- src/gui/element.rs
- src/gui/mod.rs
- src/gui/update.rs
Resolves #39.
~~We can easily optimize quite a lot here. For now I am happy with the implementation.~~
Not happy with the implementation so will spend some more time on it.
> feat: bundle addons if possible

- CHANGELOG.md
- src/gui/update.rs
- src/tukui_api.rs
There was a parsing issue with Tukui packages, and it also didn't handle classic addons very well. This is now fixed.
> fix/tukui-api endpoints.

- CHANGELOG.md
- src/gui/element.rs
- src/gui/mod.rs
- src/gui/update.rs
I've added a better onboarding experience and changed some copy so it is easier for the user to get going.
> chore: onboarding & copy

- CHANGELOG.md
- README.md
- src/config/mod.rs
- src/fs/mod.rs
- src/fs/theme.rs
- src/gui/element.rs
- src/gui/mod.rs
- src/gui/style.rs
- src/gui/update.rs
- src/main.rs
- src/theme/mod.rs
will resolve #65 
Implemented so far:
- New `Theme` struct which will hold Colors
- Store theme in app and pass to styling to use colors of theme
- Custom deserializer for `iced::Color` to deser from hex string
such as '#09ACDF'
- Only use windows subsystem on --release so we can run tests in debug
mode
> add theme feature

- CHANGELOG.md
- src/toc.rs
> fix: trim leading and trailing whitespace

- .gitignore
- Cargo.lock
- Cargo.toml
- src/parse.rs
addresses some of the items brought up in #78.
See my comments here: https://github.com/casperstorm/ajour/pull/78#issuecomment-689893369
> cleanup & optimization

- src/gui/element.rs
> fix: ui glitch in settings

- src/config/mod.rs
- src/curse_api.rs
- src/fs/addon.rs
- src/gui/element.rs
- src/gui/update.rs
- src/parse.rs
- src/tukui_api.rs
d5f9948 resolves #87 
56545d1 resolves #88
> Optimizations

- CHANGELOG.md
- src/fs/mod.rs
- src/gui/mod.rs
- src/gui/update.rs
> ensure config dir is created before concurrent operations

- CHANGELOG.md
- src/parse.rs
> fix: title fallsbacks

- src/gui/mod.rs
- src/gui/update.rs
- src/parse.rs
> change fingerprint collection to hashmap

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/addon.rs
- src/curse_api.rs
- src/gui/element.rs
- src/gui/style.rs
- src/network.rs
- src/tukui_api.rs
Resolves #49 
- I have added a website button to the details view.
- I have moved all buttons to the right to utilize the space better. The background color has also gotten a slightly increase in opacity to create some depth and overall create a more calm look:
> feat: improved details view

- crates/widgets/src/widget/header.rs
I noticed a bug in the column resizing that I somehow didn't notice before. My intent was to only have columns be resizable when hovering over the actual header. However I noticed the column could be resized anywhere along the y axis, as long as your cursor was over the correct x axis spot. I've fixed the widget to only allow resizing / change of mouse icon when hovering over the divider while inside the header bounds.
> fix resizing bounds

- src/backup.rs
- src/gui/update.rs
I fixed a small typo @mlablah found.
> fix: lastest_backup > latest_backup

- src/gui/element.rs
- src/gui/style.rs
> add channel badge

- src/gui/element.rs
- Settings was getting a bit messy. I've cleaned it up.
> feat: settings has been cleaned up

- CHANGELOG.md
- crates/core/src/parse.rs
- src/gui/element.rs
Ajour will now compare modified date to determine if we should rehash an addon.
Can you look this through @tarkah.
> feat: better cache busting

- crates/core/src/addon.rs
- src/gui/element.rs
Release channels haven't been rolled out yet, so not sure I need to changelog anything
> fix lastupdate parsing incorrectly

- CHANGELOG.md
- Makefile
- resources/linux/ajour.desktop
Resolves #137 #162
- release AppImage that can be run on any linux distro
> add appimage release

- README.md
'Curated' would imply that the list is selective but it aims
to be exhaustive.
> Alter wording in readme

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- src/cli.rs
- src/main.rs
- src/update.rs
Resolves #200 
- Add a command line option that will update all addons and exit (won't start the GUI)
> add cli feature to update all addons

- CHANGELOG.md
- crates/core/src/addon.rs
- crates/core/src/bin/parse_addon_directory.rs
- crates/core/src/config/mod.rs
- crates/core/src/curse_api.rs
- crates/core/src/fs/addon.rs
- crates/core/src/network.rs
- crates/core/src/parse.rs
- crates/core/src/tukui_api.rs
- src/gui/element.rs
- src/gui/mod.rs
- src/gui/update.rs
- src/update.rs
> refactor addon and addon parsing

- Cargo.lock
- crates/core/Cargo.toml
- crates/core/src/fs/mod.rs
> update dirs to dirs-next

- INSTALL.md
- README.md
Added Chocolatey package details.
_This PR is a draft until Chocolatey approve the package._
- Automated install via Chocolatey package manager
No code changes are required, so I've left these empty.
> Chocolatey package documentation.

- CHANGELOG.md
- crates/core/src/addon.rs
- crates/core/src/catalog.rs
- src/gui/element.rs
- src/gui/mod.rs
- src/gui/update.rs
Resolves #210 
- This PR will add a date released column in both My Addons and Catalog.
> feat: date released column

- CHANGELOG.md
- crates/core/src/addon.rs
- crates/core/src/curse_api.rs
- crates/core/src/parse.rs
Resolves #239 #277 #278
Together with WowUp we have decided, even though we are competitors, that we want to make the best we can so we joined forces and is now using the same API which is a middle man between the CurseForge API. This means we have better control going forward, and it will be open sourced as soon as possible.
> feat: ensure fingerprinting runs better

- crates/core/src/curse_api.rs
Updated the fingerprint API.
The other will stay alive.
> chore: updated fingerprint endpoint

- Makefile
Adding `tar.gz` capability to the Makefile.
> chore: updated makefile with tar.gz target

- CHANGELOG.md
- crates/core/src/catalog.rs
- src/gui/element.rs
- src/gui/mod.rs
- src/gui/update.rs
Resolves #216 #247 #230 
- Add Game Version as a column to Catalog.
- Optional columns in Catalog.
> feat: Game Version column in catalog

- CHANGELOG.md
- src/gui/element.rs
- src/gui/mod.rs
Resolves #267 
- Added a button to our website inside Settings.
> feat: added website button

- src/gui/element.rs
- src/gui/mod.rs
- src/gui/update.rs
- Forgot to set mode initially.
- Updated to more idiomatic way of doing hashmap defaults.
> fix: new state

- CHANGELOG.md
- crates/core/src/addon.rs
- crates/core/src/catalog.rs
- crates/core/src/wowi_api.rs
- src/gui/element.rs
- src/gui/mod.rs
- src/gui/update.rs
- Adds WowInterface addons to the catalog.
> feat: wowi addons in catalog

- CHANGELOG.md
- crates/core/Cargo.toml
- crates/core/src/catalog.rs
Resolves #
- Parse JSON catalogs in a thread
- - It resolves a timeout on another async req
- - It makes use of multi cpu
> Fetch and parse catalog sources asynchronously

- CHANGELOG.md
- Cargo.toml
- src/gui/mod.rs
- src/gui/update.rs
Resolves #360
- Only list categories relevant to the source selected
> Categories per source

- .github/workflows/markdown_lint.yml
- CHANGELOG.md
- INSTALL.md
- README.md
- THEMES.md
- Enforcing markdownlint in markdown files.
> chore: markdown lint

- CHANGELOG.md
- crates/core/src/theme/mod.rs
- src/gui/mod.rs
~~Resolves #~~
- Added Ferra (a new theme i came up with)
- Added [One Dark](https://github.com/joshdick/onedark.vim) copy
- Sorted all themes alphabetic in the picker 
Ferra
One Dark
> feat: added two new themes

- CHANGELOG.md
- crates/core/src/catalog.rs
- src/gui/update.rs
Resolves #379 
- use `unwrap_or_default` to prevent panic
> fix panic with catalog

- CHANGELOG.md
- src/gui/mod.rs
- Added a minimum size for Ajour window.
> feat: min window size

- Cargo.lock
- Cargo.toml
- crates/core/Cargo.toml
- crates/widgets/Cargo.toml
- crates/widgets/src/renderer/header.rs
- crates/widgets/src/widget/header.rs
- src/gui/element.rs
- src/gui/mod.rs
- src/gui/style.rs
- src/gui/update.rs
- Use new iced release instead of git, so we can publish Ajour to crates.io
- A few small api changes were needed to align w/ iced 2.0
> use iced release 0.2

- CLI.md
- README.md
- src/gui/update.rs
> chore: cli manual

- CHANGELOG.md
- crates/core/src/config/wow.rs
- crates/core/src/repository/backend/tukui.rs
- Switch to Hub api, like on Curse.
> chore: update tukui endpoint

- CHANGELOG.md
- crates/core/src/catalog.rs
- crates/core/src/network.rs
- crates/core/src/parse.rs
- crates/core/src/repository/backend/git.rs
- crates/core/src/repository/backend/tukui.rs
- crates/core/src/repository/backend/wowi.rs
- crates/core/src/utility.rs
- src/command/install.rs
- src/command/update.rs
- src/gui/mod.rs
- src/gui/update.rs
- Add `User-Agent` header to our quests. We use `ajour/version`.
> chore: added user-agent

- src/gui/element/settings.rs
- src/gui/mod.rs
- src/gui/update.rs
- Adds a reset columns button in settings.
> feat: reset columns option

- CHANGELOG.md
- crates/core/src/config/addons.rs
- crates/core/src/fs/addon.rs
- crates/core/src/fs/mod.rs
- src/gui/element/settings.rs
- src/gui/mod.rs
- src/gui/update.rs
Resolves #7
- Option in Settings do delete saved variables along side the addon.
> feat: delete saved variables

- INSTALL.md
Resolves #477 
- Fix error when installing using latest Homebrew in macOS.
I think this checklist is not relevant since this PR is simply a document change.
> docs: Fix installation instructions in INSTALL.md

- locale/da_DK.json
- locale/de_DE.json
- locale/en_US.json
- locale/fr_FR.json
- locale/ru_RU.json
- locale/se_SE.json
- src/gui/element/mod.rs
- src/gui/element/settings.rs
Settings has been reordered and has been visually adjusted to be more user friendly.
> chore: reordered and reworked settings

- CHANGELOG.md
- src/gui/element/about.rs
- src/gui/element/menu.rs
- src/gui/mod.rs
- src/gui/style.rs
Refreshed the menu with a more simple and uncluttered look.
> chore: refreshed the menu

- CHANGELOG.md
- crates/core/src/addon.rs
- src/gui/element/my_addons.rs
- src/gui/mod.rs
- src/gui/style.rs
- src/gui/update.rs
Resolves #455 #291
- Add search bar to My Addons
> feat: ability to search in My Addons

- CHANGELOG.md
- crates/core/src/addon.rs
- crates/core/src/cache.rs
- crates/core/src/catalog.rs
- crates/core/src/fs/addon.rs
- crates/core/src/network.rs
- crates/core/src/parse.rs
- crates/core/src/utility.rs
- src/gui/mod.rs
- src/gui/update.rs
- src/main.rs
Resolves https://github.com/ajour/ajour/discussions/435
- Changed to repo files rather than release.
> chore: change catalog urls

- CHANGELOG.md
- locale/cs_CZ.json
- locale/da_DK.json
- locale/de_DE.json
- locale/en_US.json
- locale/es_ES.json
- locale/fr_FR.json
- locale/hu_HU.json
- locale/nb_NO.json
- locale/pt_PT.json
- locale/ru_RU.json
- locale/se_SE.json
- locale/sk_SK.json
- locale/tr_TR.json
- src/gui/element/catalog.rs
- src/gui/mod.rs
- src/gui/update.rs
- src/localization.rs
- Added option categories column to catalog
> feat: added option categories column to catalog

- Cargo.lock
- Cargo.toml
- locale/cs_CZ.json
- locale/da_DK.json
- locale/de_DE.json
- locale/en_US.json
- locale/es_ES.json
- locale/fr_FR.json
- locale/hu_HU.json
- locale/nb_NO.json
- locale/pt_PT.json
- locale/ru_RU.json
- locale/se_SE.json
- locale/sk_SK.json
- locale/tr_TR.json
- locale/uk_UA.json
- src/gui/update.rs
- src/localization.rs
- Quite a few error has not yet been localized.
> feat: context localizations

- CHANGELOG.md
- src/gui/element/my_addons.rs
- src/gui/mod.rs
- src/gui/update.rs
- Added summary column to My Addons.
> feat: added summary column

- Cargo.lock
- Cargo.toml
- crates/core/Cargo.toml
- crates/core/src/catalog.rs
- crates/core/src/network.rs
- crates/core/src/repository/backend/curse.rs
- crates/core/src/repository/backend/git.rs
- crates/core/src/repository/backend/townlongyak.rs
- crates/core/src/repository/backend/tukui.rs
- crates/core/src/repository/backend/wowi.rs
- crates/core/src/utility.rs
- crates/weak_auras/Cargo.toml
- crates/weak_auras/src/lib.rs
- src/gui/mod.rs
Just updating a few dependencies.
> chore: update dependencies

- CHANGELOG.md
- crates/core/src/catalog.rs
- crates/core/src/config/mod.rs
- locale/cs_CZ.json
- locale/da_DK.json
- locale/de_DE.json
- locale/en_US.json
- locale/es_ES.json
- locale/fr_FR.json
- locale/hu_HU.json
- locale/nb_NO.json
- locale/pt_PT.json
- locale/ru_RU.json
- locale/se_SE.json
- locale/sk_SK.json
- locale/tr_TR.json
- locale/uk_UA.json
- src/gui/element/status.rs
- src/gui/mod.rs
- src/gui/update.rs
- src/localization.rs
Resolves ux problems with people not finding sources in the catalog.
Note this is not done yet.
-
> feat: ux update catalog

- crates/weak_auras/src/lib.rs
Resolves #573
- Invalid UTF8 characters can exist, let's toss em out.
> replace unknown UTF8 characters

- locale/cs.json
- locale/da.json
- locale/de.json
- locale/en.json
- locale/es.json
- locale/fr.json
- locale/hu.json
- locale/no.json
- locale/pt.json
- locale/ru.json
- locale/sk.json
- locale/sv.json
- locale/tr.json
- locale/uk.json
- locale/zh-Hans.json
- src/gui/element/about.rs
- src/gui/mod.rs
Don't like the multiple donation buttons in about. I've replaced it with a single button going to https://www.getajour.com/donate.
> chore: removed both donation buttons to replace them with a single one

- CHANGELOG.md
- crates/core/src/config/wow.rs
- crates/core/src/repository/backend/tukui.rs
- src/cli.rs
The TBC classic beta is using `_classic_beta_` flavor which is new.
> feat: classic beta flavor

- Cargo.lock
- Cargo.toml
- crates/core/Cargo.toml
- crates/widgets/Cargo.toml
- crates/widgets/src/widget/header.rs
- crates/widgets/src/widget/table_row.rs
- src/gui/mod.rs
> chore: updated `iced` to 0.3.0.

- CHANGELOG.md
- Cargo.lock
- crates/core/Cargo.toml
- crates/core/src/error.rs
- crates/core/src/fs/mod.rs
- crates/core/src/fs/theme.rs
- crates/core/src/theme/mod.rs
- locale/en.json
- src/gui/element/settings.rs
- src/gui/mod.rs
- src/gui/update.rs
Adds import functionality for themes created from theme builder
> add theme import feature

- CHANGELOG.md
- crates/core/src/config/mod.rs
- locale/cs.json
- locale/da.json
- locale/de.json
- locale/en.json
- locale/es.json
- locale/fr.json
- locale/hu.json
- locale/no.json
- locale/pt.json
- locale/ru.json
- locale/sk.json
- locale/sv.json
- locale/tr.json
- locale/uk.json
- locale/zh-Hans.json
- src/cli.rs
- src/command/backup.rs
- src/gui/element/settings.rs
- src/gui/mod.rs
- src/gui/update.rs
- Ability to backup screenshots
- Refactor "get_x_directory" to reuse code, also easier to add new one.
> Feature - Backup screenshots

- .github/workflows/release_to_draft.yml
- CHANGELOG.md
- Cargo.toml
- Makefile
- crates/core/Cargo.toml
- crates/core/src/addon.rs
- crates/core/src/cache.rs
- crates/core/src/fs/addon.rs
- crates/core/src/fs/theme.rs
- crates/core/src/repository/backend/curse.rs
- crates/core/src/repository/backend/hub.rs
- crates/core/src/repository/backend/tukui.rs
- crates/core/src/repository/backend/wowi.rs
- crates/core/src/utility.rs
- crates/widgets/src/renderer/table_row.rs
- src/gui/mod.rs
- src/gui/update.rs
> Revert "Feature/no self update"

- crates/core/src/config/wow.rs
- crates/core/src/repository/backend/tukui.rs
- src/gui/element/settings.rs
> Add support for Classic Era PTR

- .github/workflows/release_to_draft.yml
- Cargo.toml
- Makefile
- src/gui/update.rs
> Only package as opengl and make default for building

- CHANGELOG.md
- crates/core/src/parse.rs
Resolves issue where Ajour goes down if Wowi, or any other source returns error.
> feat: better source error handling
