- src/curse_api.rs
- src/gui/mod.rs
- src/gui/update.rs
- src/network.rs
- src/tukui_api.rs
- src/wowinterface_api.rs
resolves #45 
Haven't tested this as I don't have any WoW installed / addons on my machine. It should limit 6 connections per API host by using a shared client across all requests and specifying `max_connections_per_host(6)`
> use shared client for throttling per host

- Cargo.lock
- Cargo.toml
- src/gui/element.rs
- src/gui/mod.rs
- src/gui/update.rs
- src/main.rs
- src/utility.rs
resolves #57 
I couldn't find a hyperlink widget in `Iced` for the user to click to take them to the latest release page. For now it just replaces the version with update text styled as an error.
> check for newer version

- src/addon.rs
- src/gui/element.rs
- src/gui/mod.rs
- src/gui/style.rs
- src/gui/update.rs
resolves #37 
Fix `Ord` and `PartialOrd` to sort properly. Updatable addons sort to top, then sort by title ascending. If title's match, then sort by remote version descending.
Sort addons after folder is initially parsed, each addon metadata is downloaded (to determine if updatabable or not) and after each package is updated (to resort by name).
> make columns sortable

- src/gui/element.rs
Resolves #68.
This is a temporary fix. If we increase the cell height it breaks (again) but I'll need more time to come up with a proper solution because in my opinion it is something `iced` should be able to handle.
> fix: line height

- src/gui/mod.rs
- src/gui/update.rs
- src/parse.rs
store FingerprintCollection in memory and only allow one operation on it at a time, so concurrent tasks can't overwrite changes to the collection. We still write changes to disk after each operation makes it's updates.
> synchronize updates to FingerprintCollection

- CHANGELOG.md
- src/addon.rs
- src/curse_api.rs
- src/parse.rs
partially addresses #90. We still don't show addons with no API hit.
All addons with a curse id can be queried against curse. Previously, only addons with exact fingerprints got curse package updates. This PR identifies the gap of addons that have a Curse ID, no Tukui ID, and were not successfully fingerprinted. We then apply the curse package.
> parse non-fingerprint curse-id matches

- CHANGELOG.md
- src/config/mod.rs
resolves #96 
The `glob` crate is a little weird. I couldn't get it to match `interface/addons` even with the case insensitive option enabled. I was able to get it working by adding an actual pattern symbol within each component of the path patten, such as `?nterface/?ddons`. With this pattern, I have it working completely case insensitive. I've tested it with a bunch of combinations, including `InTeRFAcE/aDdONs`
> check for case insensitive addons folder

- src/config/addons.rs
- src/gui/update.rs
@casperstorm I got it figured out! Check out the `visit_seq` for the meat of how we handle the old array format. I tested this and it works!
I also noticed that ingored addons in the settings only showed up for the flavor at launch, but if I switched to the other flavor, it didn't show up (unless you hit refresh). I fixed in the ParsedAddons message logic so both flavors have their ignored addons added.
> deser old ignored addons format

- CHANGELOG.md
- src/addon.rs
- src/config/addons.rs
- src/config/mod.rs
- src/config/wow.rs
- src/fs/save.rs
- src/gui/element.rs
- src/gui/mod.rs
- src/gui/style.rs
- src/gui/update.rs
- src/parse.rs
This PR makes it easier to switch between flavors (retail/classic). The dropdown menu is moved to the menu row, and both directories are parsed, if there's any addons to parse.
It's a rather big refactor for a small feature, but that's because we are moving away from keeping addons in a `Vec<Addon>` but instead having them in a `HashMap` where `flavor` is key, and `Vec<Addon>` is value. This requires a little bit of plumping here and there.
Feel free to codereview as I go along, @tarkah - it's still a bit messy but you might already have comments.
> feat: able to easily select flavor from menu

- CHANGELOG.md
- src/gui/element.rs
- src/gui/style.rs
- src/gui/update.rs
Resolves #94.
This PR improves clarity of the selected row to easily see which is used as a sort key, and which direction.
> feat: improve clarity of row titles to reflect current sort state

- CHANGELOG.md
- src/gui/update.rs
Resolves #113.
Closes settings on the following interactions:
> feat: on interactions, we close settings if its shown.

- .github/ISSUE_TEMPLATE/bug_report.md
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/config/mod.rs
- src/curse_api.rs
- src/error.rs
- src/fs/mod.rs
- src/fs/theme.rs
- src/gui/update.rs
- src/main.rs
- src/network.rs
- src/parse.rs
- src/theme/mod.rs
- src/utility.rs
First commit is the meat of adding logging support for Ajour. On startup, it will create / truncate the log file so it should never grow too big and is only relevant to the last launch of the app.
- If `cargo run` it will log to console.
- If `cargo run --release` / binary is used, it will log to `$config/ajour/ajour.log`.
The rest is just going to be scattering `debug!` everywhere! I figured we can roll this out with everything as `DEBUG` and if needed, convert some stuff to `INFO` or `TRACE` as needed if there is too much noise.
> add local logging for debugging

- src/addon.rs
- src/gui/element.rs
- `remote_title` was not really used anymore, but it was the first priority when choosing name for the ignored addon in settings. This has now been corrected, and the variable is removed.
> chore: removed remote title

- CHANGELOG.md
- src/gui/element.rs
- src/gui/style.rs
- src/gui/update.rs
- Interactions will now close details view.
- Highlighted title of expanded addon.
> feat: highlight selected addon and close details on interaction

- CHANGELOG.md
- src/gui/update.rs
- When pressing update all we also updated ignored addons which is a bug. This is now resolved.
> fix: now correctly ignores ignored addons when updating all

- .cargo/config
- CHANGELOG.md
On Windows Ajour depends on Microsoft Visual C++ 2015 Redistributable being installed. If you don't have it installed, you would get an error, eg. `VCRUNTIME140_1.dll is missing`. 
I have now adjusted the build setup, so all dependencies are bundled together inside the executable. From my initial testing the size of the Ajour is still below 10mb, and still only consists of the executable, no extra files.
> feat: bundle dynlibs for x86_64

- INSTALL.md
_disclaimer: I'm very new to contributing to open source projects. Any feedback regarding my contribution is welcome and appreciated!_
I am a new Linux user and have been experimenting with gaming on Linux. Since the Twitch app was not easy to get up and running with Wine, I stumbled across this app and was excited! After following the INSTALL.md and due to my unfamiliarity with Rust apps, I had a hard time finding the compiled binary.
- Adds some clarifying markdown to indicate where the final binary is built to for Windows and Linux users.
- [n/a] Tested on all platforms changed
- [n/a] `cargo fmt` has been run on this branch
- [n/a] `cargo clippy` has been run on this branch
- [n/a] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
> Add install md to indicate app bin

- CHANGELOG.md
- src/config/mod.rs
- src/gui/element.rs
- src/gui/mod.rs
- src/gui/update.rs
Resolves https://github.com/casperstorm/ajour/projects/2#card-45378181
This adds the ability to specify application scale in the settings & persists that change to the config. Overall an easy change since `Iced` provides a scale factor on the application so we don't have to manually scale anything.
> add scaling

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/backup.rs
- src/config/mod.rs
- src/fs/backup.rs
- src/fs/mod.rs
- src/gui/element.rs
- src/gui/mod.rs
- src/gui/update.rs
- src/main.rs
This feature will allow the user to backup their Addons and WTF folder through Ajour. Once the user selects a backup directory in settings, a "Backup Now" button will be available to push. Once clicked, the app will zip the Addons and WTF folders from each flavor present on the system and save that zip file under the backup folder with name `ajour_backup_YYYY-MM-DD_HH-MM-SS.zip`. We can then parse this folder on startup and determine the most recent backup made by the user and present that datetime along with the Backup Now button.
This won't manage the backups once they are created, so it won't handle pruning old backups or restoring from backups.
> backup feature

- src/gui/update.rs
Changes UI scale slider from `0.25` to `0.1`.
> chore: changed ui-scales to 0.1

- src/fs/backup.rs
Changed compression method from `Bzip2` to `Deflated` because both Windows and macOS can't handle `Bzip2` with their default unarchivers.
> chore: changed compression to deflated

- Cargo.lock
- crates/core/Cargo.toml
Oops, I did the lib split on my linux desktop and accidently removed `dirs` as a dependency due to conditional compilation. Just caught it this morning on my windows work computer.
> fix: missing dep

- CHANGELOG.md
- crates/core/src/fs/mod.rs
- If you have a brand new macOS installation there is a chance you dont have the `.config` folder in `~`. If you don't have this folder, Ajour can't start.
- I have fixed this by creating the folder, if it isn't there.
> fix: creates config dir

- crates/core/src/addon.rs
This conditional attribute was missing and causing compilation errors for the `bins` under `ajour-core`
> missing conditional feature attribute

- CHANGELOG.md
- crates/core/src/addon.rs
- src/gui/element.rs
- src/gui/mod.rs
- src/gui/update.rs
- We decided that keeping ignored addons inside settings was confusing. We have moved them into the main addon list and is now instead using the status column to indicate if a addon is ignored or not.
> feat: move ignored addons out of settings

- CHANGELOG.md
- crates/core/src/addon.rs
- crates/core/src/config/mod.rs
- crates/core/src/curse_api.rs
- crates/core/src/tukui_api.rs
- crates/widgets/src/widget/header.rs
- src/gui/element.rs
- src/gui/mod.rs
- src/gui/style.rs
- src/gui/update.rs
Resolves https://github.com/casperstorm/ajour/projects/2#card-45790708
- Add section to settings to allow toggling visibility of columns & reordering columns
- Add optional columns (unchecked by default): Game Version, Author, Last update date, Channel
- Persist changes to config file
> add optional columns & reordering

- CHANGELOG.md
- src/gui/element.rs
- src/gui/style.rs
- We have reworked the segmented controls for selecting classic and retail. This new control should be more obvious for the user.
> feat: reworked the segmented flavor control

- Cargo.lock
- Cargo.toml
- src/main.rs
- Log panic / backtrace to log file so we can better debug issues, especially launch issues
> add panic & backtrace logging

- src/main.rs
@casperstorm I think this was the regression you were referring to. When we created `ajour-core`, we never updated our log filter to capture log events from that library
> include ajour_core in logging

- src/gui/style.rs
- Small border to unselected segmented control to add a better indication that you can press it.
> chore: added small border to segmented control

- CHANGELOG.md
- crates/core/src/addon.rs
- crates/core/src/curse_api.rs
- crates/core/src/parse.rs
For some reason CurseForge returns the a Minecraft addon called HorsePower when we hand them the hash of ActionValue addon. This caused Ajour to crash. I am now filtering out the responses so we don't get this crash in the future. Strange.
> fix: the horsepower bug is now fixed 🐴

- CHANGELOG.md
- src/gui/mod.rs
Resolves issue where users would load and se Ajour without any text.
Upstream has this issue: https://github.com/hecrj/iced/issues/537
For now we will just remove antialiasing because it's only for triangle primitives.
> chore: removed antialiasing

- CHANGELOG.md
- src/gui/mod.rs
Apparently removing AA will curse a huge footprint in memory and strange glitches. We will leave it on for now.
> chore: re-added aa due to large memory footprint without

- .github/workflows/continuous-integration.yml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crates/widgets/Cargo.toml
- crates/widgets/src/lib.rs
- src/gui/mod.rs
Resolves hopefully #163 & #153 and other issues people have where Ajour crashes on startup.
This can be built using the following command: `cargo build --no-default-features  --features opengl`
- provide an alternative build that uses OpenGL instead of wgpu (DirectX12, Vulkan, Metal). This should be a much wider supported build, at the cost of rendering performance.
> OpenGL build

- crates/core/src/catalog.rs
- src/gui/mod.rs
- src/gui/update.rs
- Abstracts away the very implicit api of injecting the All Categories into the category dropdown.
- The new interface implements both `Default` and a static function for retrieving the `all_option()` and it resembles the interface of the result size dropdown to generate a more cohesive codebase.
> feat: abstracted all categories option for a cleaner interface

- src/gui/element.rs
I've optimized the space in Settings:
> chore: tidy settings

- CHANGELOG.md
- crates/core/src/utility.rs
- src/gui/update.rs
Resolves #194 
Better logic for picking the World of Warcraft directory:
- When a user selects the root dir i'll check if any known folder (`_retail_`, or `_classic_`) is there, if yes use that dir.
- When a user selects a sub folder of the root dir (eg. `World of Warcraft/_retail_/Interface`) i'll look at the ancestors and if I find a known sub-folder to the root dir (`_retail_`, or `_classic_`) i'll use the parent of that sub-folder.
To test this run `cargo test test_wow_path_resolution --all`.
Currently only tested on macOS, will test on Windows tomorrow.
> feat: better wow path resolution

- CHANGELOG.md
- crates/core/src/parse.rs
> Fix fingerprinting errors

- CHANGELOG.md
- crates/core/src/addon.rs
Fixes #199
A little bug had sneaked pass my nose where the alpha release channel didn't always show the correct version. Sorry about that!
> fix: alpha channel didn't always correctly show the newest value

- .github/workflows/release_to_draft.yml
We didn't add `MACOS=1` to mac builds which meant we wouldn't set `MACOSX_DEPLOYMENT_TARGET="10.11"` which means that the build would only work on the latest version of macOS.
> fix: add env variable to mac builds in workflow

- .github/workflows/release_to_draft.yml
- CHANGELOG.md
- crates/core/src/catalog.rs
- src/gui/element.rs
- src/gui/mod.rs
Resolves #223
- It is now possible to open the addon website for more information by pressing the title in the catalog.
> feat: able to open addon website from catalog

- CHANGELOG.md
- crates/core/src/fs/addon.rs
- src/gui/update.rs
This fixes a couple potential bugs... If an update to an addon has a different list of `AddonFolder` than the currently installed addon, it used to leave those old folders on the filesystem. Then the new fallback logic would show those orphaned folders as "Uknown". We now delete all top level folders based on the `Addon`s `folders` prior to extracting the new addon folders.
We also make sure that these new addon folders are parsed and assigned to the addon not only on Catalog Install, but on Update as well. This should always keep the folders of the Addon accurate.
> always refresh folders on update or install

- CHANGELOG.md
- crates/core/src/addon.rs
Resolves #270
- Fixed a bug in the logic for selecting a relevant release package. Issue was that if a addon used some of the channels, but not all the logic was flawed. This is now fixed.
> fix: updated logic for release channels

- CHANGELOG.md
- crates/core/src/parse.rs
Resolves #284.
- We now show modules if they are a match. Previously I added some logic to avoid this, but that was a mistake. We all make mistakes apparently.
> chore: reverted hide of some modules

- crates/core/src/addon.rs
- In a rare case we assumed a little too much, and was met with a crash. I am playing a bit more defensive now and do not assume the data from CurseForge is good.
> chore: unwrap could cause ajour to crash

- crates/core/src/addon.rs
- crates/core/src/curse_api.rs
Previously we did a fingerprint check to CurseForge. This we don't do anymore now.
For backlog @tarkah – let's talk about this when you are back.
> fix: remove fingerprint dependency from when you install from catalog

- CHANGELOG.md
- crates/core/src/parse.rs
Resolves issue with Altoholic brought up in Discord
- Any folder with a curse id that is already successfully mapped via an exact fingerprint match shouldn't allow a new addon to be created from that curse id. I've fixed a logic gap that allowed this to happen previously.
> fix bug creating addons from already matched curse ids

- .github/FUNDING.yml
- README.md
- src/gui/element.rs
- src/gui/mod.rs
A code optimization that removes an unnecessary clone of the config to be able to pass it elsewhere as a mutable reference.
This doesn't resolve any outstanding issue and I don't believe that this requires a CHANGELOG entry.
> Fixed unnecessary config clone

- CHANGELOG.md
- crates/core/src/utility.rs
Resolve issue posted on Discord:
Updated the regex for parsing changelog. It will not catch and fix the above.
> fix: better regex for parsing changelog

- CHANGELOG.md
- crates/core/src/addon.rs
- crates/core/src/lib.rs
- crates/core/src/parse.rs
- crates/core/src/wowi_api.rs
- src/gui/element.rs
- src/gui/mod.rs
- src/gui/update.rs
Resolves #224
- Add WoWInterface as a source.
- Add "Source" column as a new column to see where an addon is matched towards.
- Removed "Unknown" addons from Status column. and moved it to Source column.
> feat: identify wowinterface addons 

- CHANGELOG.md
- crates/core/src/addon.rs
- crates/core/src/network.rs
- If you installed a addon through the catalog which had no stable release, Ajour couldn't handle it.
- I've made a fallback solution now so it tries tries different release channels before failing in the end.
> fix: no stable package

- Cargo.lock
- Cargo.toml
- src/gui/element.rs
Currently if you are running version `0.5.0` and latest release is `0.4.4` Ajour will tell you to "update" to `0.4.4` because the logic for this check is just `!=`. I have changed that and is now using a crate which handles multiple different version systems. Reason for pulling this in is that it could also be useful going forward with Github/Gitlab sources.
> chore: version compare

- CHANGELOG.md
- src/gui/element.rs
- src/gui/mod.rs
- src/gui/update.rs
Resolves multiple problems related to the fact that we had a single `AjourState` enum controlling loading state for multiple areas in the app.
- Idea is to split it into a `HashMap<Mode, State>` so each mode have its own state.
- `Mode:MyAddon` now takes `flavor` we each `flavor` also has a `State`.
- Error is removed from `State` and is now living on the `Ajour` enum.
I am missing a few things still, one thing I would like to tackle is how to properly handling multiple flavors loading.
> chore: refactor state & mode

- Cargo.lock
- crates/core/Cargo.toml
- crates/core/src/addon.rs
- crates/core/src/bin/parse_addon_directory.rs
- crates/core/src/cache.rs
- crates/core/src/catalog.rs
- crates/core/src/lib.rs
- crates/core/src/parse.rs
- crates/core/src/tukui_api.rs
- crates/core/src/wowi_api.rs
- src/gui/mod.rs
- src/gui/update.rs
- src/update.rs
Resolves adding Tukui and WowI reliably to catalog
- Cache addon api and folder grouping data for Tukui and WowI addons installed through catalog since those APIs don't give us fingerprinting / modules like Curse and the addon folders are unreliable for getting repo IDs and impossible to determine grouping off of
- Use this cache when parsing addons so we can reliably group / get repo metadata for these addons
> feat: Addon Cache

- crates/core/src/parse.rs
Partial fixes #326.
- Updated the regex for parsing toc titles.
- Refactored so we now use `lazy_static` to avoid compiling the same regexes multiple times
- Added tests
> chore: update title regex

- src/gui/mod.rs
- src/gui/update.rs
As discussed we think it will be too confusing to show "All Sources" in Catalog as it grows since addons can appear in multiple sources confusing users.
If `Foo` appears right next to each other, which to choose? UX wise this is not optimal.
> feat: removed "all source"

- Cargo.lock
- crates/core/Cargo.toml
Updated crates. Even though some was `patch `and `major`, everything seems to work.
Let's double check though :-)
> chore: update crates

- crates/core/src/addon.rs
- crates/core/src/cache.rs
- crates/core/src/fs/addon.rs
- src/gui/element.rs
- src/gui/mod.rs
- src/gui/update.rs
- Do not insert the catalog addon into our main addons vec until it has
been successfully unpacked.
- Make sure any existing addon that has the same addon folders as our
newly installed addon is removed prior to inserting the new addon to
prevent dupliates.
- Make sure addon cache entries are removed when the addon is deleted
or when the same addon is installed via catalog from the Curse source
> fix catalog install flow

- CHANGELOG.md
- crates/core/src/addon.rs
- crates/core/src/catalog.rs
- crates/core/src/parse.rs
- src/gui/mod.rs
Fixes #336
- If we don't get `game_version` from API, we will fallback to using a parsed `Interface` value from the TOC file.
> feat: interface fallback

- CHANGELOG.md
- crates/core/src/config/mod.rs
- src/gui/element.rs
- src/gui/mod.rs
- src/gui/update.rs
Resolves #340 
- Add toggles in settings for Addons and WTF folder, only selected folders get backed up
- If neither are selected, Backup Now button is disabled
> add backup folder toggle

- crates/core/src/catalog.rs
- src/gui/element.rs
- src/gui/mod.rs
Just a small cleanup PR to fix some of the TODOs we had.
Going forward I would like to a be a little more strict on our `TODOs` and comments in general.
We should follow:
```
// TODO (casperstorm): This is a todo with some information.
```
Or combined with a relevant source:
```
// TODO (casperstorm): Currently we have a problem, but should be fixed eventually.
// @see https://getajour.com
```
> chore: handle todos

- CHANGELOG.md
- src/gui/element.rs
> fix: too short button containers in settings (332)

- CHANGELOG.md
- crates/core/src/config/mod.rs
- src/gui/element.rs
- src/gui/mod.rs
- src/gui/style.rs
- src/gui/update.rs
- Added a option to hide ignored addons.
> feat: hide ignored addons

- CHANGELOG.md
- crates/core/src/addon.rs
- We didn't correctly filter away the empty strings from API which meant we would never fallback to TOC.
> fix: game version fallback to toc could in some cases fail

- CHANGELOG.md
- src/gui/update.rs
Makes it so, in the catalog, if you click on 'date released', it sorts descending by default.
I believe that’s what 99.9 % of users expect.
> Catalog date order on first click

- CHANGELOG.md
- src/cli.rs
- src/command/backup.rs
- src/command/mod.rs
- src/main.rs
Resolves feature requested in discord
- add option to backup folders via command line
- flavors and backup folders can be specified
> add backup via cli

- src/gui/update.rs
- [It seems ](https://github.com/casperstorm/ajour-catalog/releases?after=2020-11-20-00-29) catalog is done 00:3x and not 00:0x. I've updated timer to 00:40.
> fix: refresh catalog 00:40 instead of 00:05

- CHANGELOG.md
- crates/core/src/addon.rs
- src/gui/element.rs
- src/gui/update.rs
- If download fails on a addon we show a  retry button.
> chore: refactored AddonState

- CHANGELOG.md
- Cargo.lock
- crates/core/Cargo.toml
- crates/core/src/error.rs
- crates/core/src/fs/backup.rs
Resolves #385
- Convert windows path separator from `\` to `/` before writing name to zip file
> normalize windows path separator for zipping

- CHANGELOG.md
- crates/core/src/addon.rs
- crates/core/src/parse.rs
- crates/core/src/repository/backend/curse.rs
- crates/core/src/repository/backend/git.rs
- crates/core/src/repository/backend/mod.rs
- crates/core/src/repository/backend/tukui.rs
- crates/core/src/repository/backend/wowi.rs
- crates/core/src/repository/mod.rs
- crates/core/src/utility.rs
- src/gui/element.rs
- src/gui/mod.rs
- src/gui/update.rs
- Not happy with how complex the changelog system is. Also not happy with poorly we are parsing it. It will never be perfect to what I would like because of the different formats. This change will remove the parsed changelogs and add a "Changelog" button in details which opens directly to the relevant page with a changelog.
> feat: simplify changelogs

- crates/widgets/src/widget/table_row.rs
Resolves #416 
Changed `Event::Mouse(mouse::Event::ButtonReleased(mouse::Button::Left)) `on `table_row`, to `Event::Mouse(mouse::Event::ButtonPressed(mouse::Button::Left))` to avoid having uncaptured event from other widget
> Fix for bug on #416

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/gui/update.rs
Resolves #398
- When user searches for an addon in the catalog, use a fuzzy match instead of basic string contains logic.
- Results are sorted by fuzzy match score by default. Columns can still be sorted after the fact, but typing a new character into the query box resets the sort back to fuzzy match score.
> add fuzzy match to catalog search

- CHANGELOG.md
- crates/core/src/addon.rs
Resolves #422
- Ignored addons are now correctly sorted again.
> fix: ignored addons are now sorted correctly

- CHANGELOG.md
- crates/core/src/cache.rs
- crates/core/src/error.rs
- crates/core/src/parse.rs
- Remove addon cache entries when it's folders no longer exist on the filesystem
> remove addon cache entries on missing addon folders

- CHANGELOG.md
- crates/core/src/addon.rs
- crates/core/src/config/addons.rs
- crates/core/src/network.rs
- crates/core/src/repository/mod.rs
- src/command/install.rs
- src/command/update.rs
- src/gui/element/my_addons.rs
- src/gui/element/settings.rs
- src/gui/mod.rs
- src/gui/update.rs
Resolves #236 #185 #231
- We will create a way to control release channels at a global level.
> feat: global addon release channel

- src/gui/update.rs
Resolves issue where if you go from `stable` to `default` it wouldn't remove `stable` from config.
> chore: fix for selecting default release channel

- CHANGELOG.md
- src/gui/element/catalog.rs
- src/gui/element/my_addons.rs
There was a regression in 0.5.4 once highlight rows was enabled that removed padding from the Title of My Addons and Catalog. The text for these used to be wrapped in a Button, which by default has a padding of 5 on it's contents. I fixed this by adding the padding of 5 back on the text's container. This also fixes the regression where the title would visibly "wrap" without this padding.
You can see the default padding of a button here:
https://github.com/hecrj/iced/blob/master/graphics/src/widget/button.rs#L24
> add padding back to titles

- CHANGELOG.md
- crates/weak_auras/src/lib.rs
Resolves #442 
- Apparently you can submit auras without having an account so `username `is null. I did a quick fix to make it optional.
- @tarkah can you look at if there's a more smooth way of handling this?
> fix: username is now optional

- CHANGELOG.md
- crates/core/src/addon.rs
- crates/core/src/error.rs
- crates/core/src/repository/backend/git.rs
- src/gui/element/my_addons.rs
Resolves #438
- Added "Beta / Alpha" release channel support for GitHub addons. Releases marked
as "pre-release" on GitHub will show as an update when the addon is marked as
"Beta" or "Alpha". Releases not marked as "pre-release" will show up for "Stable".
- Fixed addon title letter casing for GitHub addons by using the actual repository
name instead of parsed repo from the user inputted URL
> add pre-release channel for github addons

- CHANGELOG.md
- src/gui/update.rs
Resolves #433
- `Interface` folder root is included in the zip backup when `AddOns` is selected.
Some users store proprietary data alongside the `AddOns` folder that they'd like
included during backup.
> include Interface root in AddOns backup path 

- CHANGELOG.md
- crates/core/src/config/mod.rs
- src/gui/element/catalog.rs
- src/gui/element/my_addons.rs
- src/gui/element/my_weakauras.rs
- src/gui/element/settings.rs
- src/gui/mod.rs
- src/gui/style.rs
- src/gui/update.rs
- Row colors now alternate by default for better accessibility. This can be turned
off in settings under the UI section's "Alternate Row Colors" checkbox.
> add alternating row colors 

- CHANGELOG.md
- src/gui/mod.rs
Resolves #427 
- Disabled minimum window size on Linux because it causes the window to become non-resizable.
> fix: linux resizable

- CHANGELOG.md
- src/main.rs
Resolves #457
- Set custom config dir before setting up logging, not after :P
> set custom config dir before setting up logging

- CHANGELOG.md
- crates/core/src/parse.rs
- src/gui/mod.rs
Resolves a little pixel height difference in catalog. See blow.
> fix: catalog pixel difference

- CHANGELOG.md
- crates/core/src/addon.rs
- crates/core/src/parse.rs
- src/gui/element/my_addons.rs
Resolves better UX.
- `Force install` had little to no value.
> chore: removed force install from addons

- CHANGELOG.md
- Cargo.lock
- crates/weak_auras/Cargo.toml
- crates/weak_auras/src/lib.rs
Resolves #465, #466
- Make aura display field Version an Option since it's not always present. If not present, we will try to use the version from the URL field.
- Fix the API calls to percent encode the parameters. Some slugs have `&` symbol in it, causing error in built URL
> weak auras fixes

- Cargo.lock
- Cargo.toml
- src/gui/element/catalog.rs
- src/gui/element/my_addons.rs
- src/localization.rs
`timeago` crate had support for localization, i've implemented it with fallback to english.
> feat: relative time localization

- CHANGELOG.md
- src/gui/update.rs
Resolves #462
- Filter out scores that are negative. When I first implemented this, I thought it would only return positive scores by default but never checked. This helps remove a ton of non-related results.
- Increase the penalty for when gaps occur in matches characters vs the search pattern. This helps push even more results negative and cleans up the results. We prefer matches that closely match the search pattern or at least have consecutive characters and not too many spaces between matching characters.
> fuzzy match tweaks

- CHANGELOG.md
- src/gui/element/my_weakauras.rs
Resolves #500
- Able to press refresh if API is down.
> fix: gui adjustment and ability to refresh at all times

- CHANGELOG.md
- src/gui/update.rs
Resolves #517 
- Score title and description separately, with a higher weighting to title. Use the max of those 2 scores.
- This should help sort the matches better on title first, which is more relevant generally to what the user wants to see
> tweak search settings

- CHANGELOG.md
- Cargo.lock
- crates/core/src/addon.rs
- crates/core/src/cache.rs
- crates/core/src/catalog.rs
- crates/core/src/config/wow.rs
- crates/core/src/error.rs
- crates/core/src/parse.rs
- crates/core/src/repository/backend/mod.rs
- crates/core/src/repository/backend/townlongyak.rs
- crates/core/src/repository/mod.rs
- src/gui/mod.rs
- src/gui/update.rs
Resolves #512 
- Add townlong-yak addon support via the hub api
> add support for townlong-yak addons

- CHANGELOG.md
- crates/core/src/config/mod.rs
- src/gui/update.rs
Resolves #528 
- Ajour will now try to create `Interface/Addon` if they don't exists in flavor directory.
> fix: empty flavor folders

- crates/core/src/catalog.rs
- src/gui/mod.rs
- src/gui/update.rs
This will resolve the us being able to keep adding sources to the catalog without breaking as just happened.
> fix: catalog source fallback

- crates/core/src/parse.rs
- crates/core/src/utility.rs
- src/gui/element/catalog.rs
Formats the townlong-yak game versions from catalog into the what we use the other places.
> fix: format townlong-yak game versions

- src/gui/mod.rs
- src/localization.rs
Resolves:
I don't like the way we worded WeakAura updates. I think we should move to "Completed" just like addons and then still leave the  "Finish ingame" message we have:
> fix: wording in weakauras

- src/command/update_addons.rs
Resolves: 
Running CLI update when theres updates for TownlongYak addons kept saying they could be updated.
It seems to be because we dont update the cache. Can you confirm this, @tarkah?
> fix: update cache when download townlong addons

- CHANGELOG.md
- src/gui/update.rs
Resolves #
- For users with only a single account, automatically pick the account when in the weak aura view
> For users with only a single account, automatically pick the account when in the weak aura view

- CHANGELOG.md
- crates/core/src/fs/addon.rs
- When updating an addon, make sure all folders it had _before_ the update are deleted. This helps prevent orphaned folders from being created, which happens notably with addons like DBM.
> remove old addon folders when updating

- crates/core/src/fs/mod.rs
Fixes regression introduced from #579. All files under the data
directory implement the PersistentData trait which will make sure the
data directory exists before saving under it. However logging doesn't
follow this pattern and would try to create a file before we ensured
data directory exists.
> fix / #579 regression

- CHANGELOG.md
- src/command/backup.rs
- src/command/install.rs
- src/command/update_addons.rs
- src/command/update_weakauras.rs
Resolves #589 
- Issue is that we looped all flavors and if one failed we bailed out. I'll now loop only valid flavors (flavors added).
> fix: multiple paths should be working with CLI again

- CHANGELOG.md
- src/gui/update.rs
resolves #596.
- Auto refresh did not respect excluded addons.
> fix: auto refresh respects excluded

- crates/core/src/cache.rs
- crates/core/src/config/mod.rs
- crates/core/src/config/wow.rs
- crates/core/src/error.rs
- crates/core/src/parse.rs
- crates/core/src/repository/backend/tukui.rs
- crates/core/src/utility.rs
- crates/weak_auras/src/error.rs
- src/cli.rs
- src/command/backup.rs
- src/gui/mod.rs
- src/gui/update.rs
Resolves clippy warning from running Ajour with Rust 1.51.0
> fix: clippy warning from rust 1.51.0

- CHANGELOG.md
- src/gui/update.rs
Resolves issue where if you only have a single account, it was never saved to the config.
> fix: save single account to config

- crates/core/src/catalog.rs
Use in favor of #612
- Skip de serializing unknown flavors in GameVersion and filter out any catalog items that have an empty game_versions array.
> skip catalog addons with unknown game flavor

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crates/core/src/config/mod.rs
- locale/en.json
- src/gui/element/settings.rs
- src/gui/mod.rs
- src/gui/update.rs
- src/main.rs
- src/tray/autostart.rs
- src/tray/mod.rs
Resolves our biggest request, sys-tray for windows!
- New setting "Close to System Tray" for Windows
- When this is selected, a system tray icon will be created.
- Pressing close will hide Ajour. It can be opened by double clicking the tray icon, or right clicking tray icon -> show
- When enabled, Ajour can only be closed via right click tray icon -> exit (we can't hook / override the Minimize button w/ Iced but as of 0.3, we can with the Close icon).
> add sys tray support for windows

- crates/core/src/catalog.rs
- crates/core/src/parse.rs
- src/gui/element/catalog.rs
- src/gui/mod.rs
- src/gui/update.rs
- This is a migration from github.com/ajour/ajour-catalog to github.com/ajour/catalog.
> feat: migration to new catalog repo

- README.md
Resolves #
- Found a link to a deleted THEMES.md updated to scroll down to themes section instead.
> Fixed old theme link (I think)

- CHANGELOG.md
- Cargo.lock
- crates/core/Cargo.toml
- crates/core/src/addon.rs
- crates/core/src/fs/addon.rs
Resolves first issue in #660
- Use file_name over file_stem, then properly remove .lua and .lua.bak
> properly remove .lua and .lua.bak files

- src/gui/element/menu.rs
- src/gui/element/my_addons.rs
- src/gui/element/my_weakauras.rs
- src/gui/element/status.rs
- src/gui/mod.rs
- src/gui/update.rs
Resolves #649
- When encountering an error, it is now possible to attach it to the current mode, which will then display it on the screen rather than in the little error box top right. This means, e.g., in the case of problems reaching the host, we write that rather than "No addons found". See the picture below as an example. I've chosen to keep the error box top right because it is still used for updating, unpacking, hashing errors.
- We don't have `State::Start` anymore, this made little sense anyway. We now have `Ready` `Loading` and `Error`.
> feat: better ui for displaying errors to the user

- crates/core/src/config/mod.rs
- src/gui/element/settings.rs
Since `Fonts` folder is a user generated folder, we only want to show the option to back it up if it exist.
> feat: only show Fonts backup option if exsist

- src/gui/element/settings.rs
We now check all flavors for any font folder.
> fix: check flavors for font folder

- CHANGELOG.md
- crates/core/src/parse.rs
- Changes relevant regexes to raw regexes (Thanks @Bananaman)
Note: this needs to be proper tested.
> fix: parsing regexes coverted to raw strings

- CHANGELOG.md
- src/gui/element/status.rs
- src/gui/mod.rs
- src/gui/update.rs
Resolves #717 
- Adds a retry button under the error to try again.
> feat: retry buttons

- CHANGELOG.md
- crates/core/src/parse.rs
> Updated regex to handle new toc files.

- CHANGELOG.md
- crates/core/src/config/mod.rs
- locale/en.json
- src/gui/element/settings.rs
- src/gui/mod.rs
- src/gui/update.rs
* Resolves issue where people don't want any keybindings in ajour.
* Resolves issue where keybind ALT + S would trigger S meaning that all modifiers was ignored. This caused problems for eg. Windows Snippet etc.
> Option to disable keybindings
